# version: '3.7'

services:
    # app:
    #     build:
    #         context: ./docker/php
    #         dockerfile: Dockerfile
    #     image: laravel-app
    #     container_name: laravel-app
    #     restart: unless-stopped
    #     working_dir: /var/www
    #     volumes:
    #         - .:/var/www
    #     networks:
    #         - laravel-network
    #     expose:
    #         - "9000"

    # nginx:
    #     image: nginx:latest
    #     container_name: nginx
    #     restart: unless-stopped
    #     volumes:
    #         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #         - ./docker/nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    #         - .:/var/www
    #     ports:
    #         - "8080:80"
    #     depends_on:
    #         - app
    #     networks:
    #         - laravel-network

    # mysql:
    #     image: mysql:5.7
    #     container_name: mysql
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: beernopro
    #         MYSQL_USER: root
    #         MYSQL_PASSWORD:
    #     volumes:
    #         - dbdata:/var/lib/mysql
    #     ports:
    #         - "3306:3306"
    #     networks:
    #         - laravel-network

    mysql:
        image: demo_mysql:v1
        container_name: demo_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: beernopro
            MYSQL_USER: root
            MYSQL_PASSWORD:
        # volumes:
        #     - dbdata:/var/lib/mysql
        # networks:
        #     - laravel-network

# volumes:
#     dbdata:

# networks:
#     laravel-network:
#         driver: bridge
